name: eureka
version: '1.0'
summary: archi m'aide
description: Super Cool App that founds everything!

confinement: strict
base: core18

parts:
  eureka:
    plugin: flutter
    source: https://github.com/kenvandine/super-cool-app.git
    flutter-target: lib/main.dart

apps:
  eureka:
    command: archimaide
    extensions: [flutter-dev]
